# maximum : the best value possible
# minimum : the worst value possible
# attributes : the amounts by wich the attributes is multiply to calculate the value
# range : creates a range and get a random number in that range

# ex:

#   by_projectile:
#     enable: true
#     function:
#     strength: 0.333
#     dexterity: 0.666
#     maximum: 2.5
#     minimum: 0.05
#     range: 2.0
#
# if max_stats is infinite, will use 100
# multiplier = [(maximum - minimum)/max_stats] * [0.333 * strength + 0.666 * dexterity] + minimum
# baseDamage = getDamage() * multiplier;
# newDamage = (baseDamage - range) + (Math.random() * (baseDamage + range))
# setDamage(newDamage);
#
# if there is no range. the damage is just multiplier by the multiplier
# in this exemple, a top level player(100) with 100 strength and 100 dexterity with full bow load will damaged
# is target with 23 to 27 damage. max bow damage in minecraft = 10 so 10*2.5 = 25 +- 2 = 23 -27;



settings:
  first_lvl_exp: 75 # experience needed for the first level
  max_lvl: 100 # maximum level. value from 0 to -infinite = infinite number of level
  max_stats: 100 # maximum attributes for each stats. zero and negative values = infinite
  allow_deduction_points: false # allow player to deduct atributes. for exemple : /mcrpg add strength -1
  can_switch_class: false # allow player to switch class. it will apply attributes changes accordingly
  can_switch_race: false # allow player to switch race. it will aplly attributes changes accordingly
  allow_stats_reset: false; # allow player to reset stats. it will reset to default race and class. player will keep is level and gained points
  allow_complete_reset: false; # allow player to reset stats complitetely. will remove class and race. will also reset points and gained level
  points_per_lvl: 2 # number of points a player gains on each level up
  starting_points: 3 # number of points a player get a start
  auto_save: true # enable auto saving
  save_interval: 360 # auto saving interval in second(6min by default). auto_save must be true
  exp_loss_on_death: 15 # pourcentage of experience a player lose on death. Ex : if player has 100xp, after death he will have 75. cannot deduct a level
  debug: false # debug mode. show stuff in console
  mana_regen_interval: 5 # interval between each mana regen for all connected players. if you change this value, you must rebalance mana regeneration mathematics.
  automatic_server_difficulty: true # will change minecraft server difficulty based on average player lvl. 0 to 25 = easy, 25 to 55 = medium, 55 and more = hard
  maths: # everything needed to calculate damage, resitance, etc
   next_lvl_multiplier: 1.1 # level multiplier. next level = (current level * multiplier) + current level
   natural_xp_gain_multiplier: 1.0 # multiplier by wich natural occuring experience(mob kill, mining, farming, etc) is multiply
  on_player_kills_player:
   enable: true # wheither are not to enable this
   base_exp: 25 # base experience a player get when killing another player
   killer_level_gain_multiplier: 0.5 # multiplier by wich base exp is multiply by level
   level_difference_multiplier: 0.5 # multiplier by wich base exp is multiply by level difference between players (low lvl player kill high lvl player = higher exp gain and vice-versa)
  on_player_attack_entity: # maximum doesnt necesseraly mean the higher value possible. it is meant to be the best value possible
   chance_of_creating_magic_attack: # = [(max-min)/max_stats] * [1 * intelligence + 0 * dexterity] + min
    enable: true # wheither or not you wich to enable
    function: #ex: 0.01 * (  0.75 * {0} + 0.25 * {1} ) + 0.0, intelligence, dexterity
    maximum: 0.5 # maximum (50%)
    minimum: 0.0 # minimum (0%)
    intelligence: 1.0 # the amount by wich player intelligence is multiply by
    dexterity: 0.0 # the amout by wich player dexterity is multiply by
   creating_magic_attact: #duration = (max - min / max_stats) * (intelligence * 0.75 + dexterity * 0.25) + min
    enable: true
    maximum_duration: 10.0
    minimum_duration: 0.0
    intelligence_on_duration: 0.75
    dexterity_on_duration: 0.25
    maximum_harm_amplifier: 3.0
    maximum_poison_amplifier: 4.0
    maximum_slow_amplifier: 5.0
    maximum_weakness_amplifier: 5.0
    maximum_wither_amplifier: 5.0
    minimum_harm_amplifier: 3.0
    minimum_poison_amplifier: 4.0
    minimum_slow_amplifier: 5.0
    minimum_weakness_amplifier: 5.0
    minimum_wither_amplifier: 5.0
    intelligence_on_harm_amplifier: 1.0
    intelligence_on_poison_amplifier: 1.0
    intelligence_on_slow_amplifier: 1.0
    intelligence_on_weakness_amplifier: 1.0
    intelligence_on_wither_amplifier: 1.0
   by_weapon:
    enable: true
    function:
    strength: 1.0
    dexterity: 0.0
    maximum: 2.5
    minimum: 0.05
    range: 2.0
   by_potion:
    enable: true
    function:
    intelligence: 85
    dexterity: 0.15
    maximum: 2.5
    minimum: 0.05
    range: 2.0
   by_projectile:
    enable: true
    function:
    strength: 0.333
    dexterity: 0.666
    maximum: 2.5
    minimum: 0.05
    range: 2.0
  on_player_get_damaged:
   by_magic:
    enable: true
    function:
    maximum: 0.333
    minimum: 1.0
    intelligence: 0.15
    magic_resistance: 0.85
   by_fire:
    enable: true
    function:
    maximum: 0.333
    minimum: 1.0
    defence: 0.25
    magic_resistance: 0.6
    intelligence: 0.15
   by_explosion:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 0.85
    strength: 0.15
   by_fall:
    enable: true
    function:
    maximum: 0.5
    minimum: 1.0
    defence: 0.25
    agility: 0.75
   by_contact:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   by_projectile:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   by_weapon:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   reducing_bad_potion_effect:
    enable: true
    function:
    maximum: 0.01
    minimum: 1.0
    range: 0.15
    magic_resistance: 0.75
    intelligence: 0.25
   chance_of_removing_magic_effect:
    enable: true
    function:
    maximum: 0.25
    minimum: 0.0
    magic_resistance: 0.70
    intelligence: 0.2
    dexterity: 0.1
  on_player_shoot_bow:
   enable: true
   function:
   min_dexterity_for_max_precision: 50.0
   range: 1.5
  on_player_consume_potion:
   enable: true
   function:
   range: 0.1
   maximum: 2.0
   minimum: 1.0
   intelligence: 1.0
  player_attributes:
   movement_speed:
    enable: true
    function:
    maximum: 0.4
    minimum: 0.15
    agility: 1.0
    dexterity: 0.0
   attack_speed:
    enable: true
    function:
    maximum: 15.0
    minimum: 2.0
    agility: 0.85
    dexterity: 0.15
    strength: 0.0
   total_mana:
    enable: true
    function:
    intelligence: 1.0
   total_health:
    enable: true
    function:
    heath: 1.0
   mana_regen:
    enable: true
    function:
    maximum: 5.0
    minimum: 0.0
    intelligence: 1.0
   luck:
    enable: true
    function:
    maximum: 512
    minimum: 0
    intelligence: 0.85
    dexterity: 0.0
    agility: 0.15
   knockback_resistance:
    enable: true
    function:
    maximum: 0.99
    minimum: 0.0
    strength: 0.5
    dexterity: 0.0
    agility: 0.0
    defence: 0.5
   mob_follow_range:
    enable: true
    function:
    maximum: 1
    minimum: 64
    agility: 0.5
    intelligence: 0.25
    dexterity: 0.25




