# first_lvl_exp: experience needed for the first level
# max_lvl: maximum level. -1 = infinite
# max_stats: maximum attributes for each stats. -1 = infinite
# next_lvl_multiplier: experience needed for next level =  nextlvl += nextlvl * <number>
# can_switch_class: allow player to switch class. Will modify attributes based on the class difference
# allow_stats_reset: allow player to reset stats. Will reset stats to current class base attributes
# points_per_lvl: the amounts of points a player gets on every lvl up
# starting_points: number of points player get when first join
# auto_save: enable automatic saving
# save_interval: interval in seconde between each save
# exp_loss_on_death: amount(%) of experience loss when player dies
# exp_on_player_kill: base experiece when player kills another player. Will increase if the lvl difference is high
# mana_regen_interval: interval in seconds between each regeneration. mana regeneration is calculated with player intelligence
#   if you reduce the interval, regeneration will be faster and vice verca.


settings:
  first_lvl_exp: 75
  max_lvl: 100
  max_stats: 100
  can_switch_class: false
  can_switch_race: false
  allow_stats_reset: false;
  allow_complete_reset: false;
  points_per_lvl: 2
  starting_points: 3
  auto_save: true
  save_interval: 360
  exp_loss_on_death: 25
  exp_on_player_kill: 25
  debug: false
  mana_regen_interval: 5
  automatic_server_difficulty: true
  maths:
   next_lvl_multiplier: 1.1
   natural_xp_gain_multiplier: 1.0
  on_player_kills_player:
   enable: true
   killer_level_gain_multiplier: 0.5
   level_difference_multiplier: 0.5
  on_player_attack_entity:
   chance_of_creating_magic_attack:
    enable: true
    function:
    maximum: 0.5
    minimum: 0.0
    intelligence_effect: 1.0
    dexterity_effect: 0.0
   creating_magic_attact: #duration = (max - min / max_stats) * (intelligence * 0.75 + dexterity * 0.25) + min
    enable: true
    maximum_duration: 10.0
    minimum_duration: 0.0
    intelligence_on_duration: 0.75
    dexterity_on_duration: 0.25
    maximum_harm_amplifier: 3.0
    maximum_poison_amplifier: 4.0
    maximum_slow_amplifier: 5.0
    maximum_weakness_amplifier: 5.0
    maximum_wither_amplifier: 5.0
    minimum_harm_amplifier: 3.0
    minimum_poison_amplifier: 4.0
    minimum_slow_amplifier: 5.0
    minimum_weakness_amplifier: 5.0
    minimum_wither_amplifier: 5.0
    intelligence_on_harm_amplifier: 1.0
    intelligence_on_poison_amplifier: 1.0
    intelligence_on_slow_amplifier: 1.0
    intelligence_on_weakness_amplifier: 1.0
    intelligence_on_wither_amplifier: 1.0
   by_weapon:
    enable: true
    function:
    strength: 1.0
    dexterity: 0.0
    maximum: 2.5
    minimum: 0.05
    range: 2.0
   by_potion:
    enable: true
    function:
    intelligence: 85
    dexterity: 0.15
    maximum: 2.5
    minimum: 0.05
    range: 2.0
   by_projectile:
    enable: true
    function:
    strength: 0.333
    dexterity: 0.666
    maximum: 2.5
    minimum: 0.05
    range: 2.0
  on_player_get_damaged:
   by_magic:
    enable: true
    function:
    maximum: 0.333
    minimum: 1.0
    intelligence: 0.15
    magic_resistance: 0.85
   by_fire:
    enable: true
    function:
    maximum: 0.333
    minimum: 1.0
    defence: 0.25
    magic_resistance: 0.6
    intelligence: 0.15
   by_explosion:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 0.85
    strength: 0.15
   by_fall:
    enable: true
    function:
    maximum: 0.5
    minimum: 1.0
    defence: 0.25
    agility: 0.75
   by_contact:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   by_projectile:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   by_weapon:
    enable: true
    function:
    maximum: 0.3333
    minimum: 1.0
    defence: 1.0
   reducing_bad_potion_effect:
    enable: true
    function:
    maximum: 0.01
    minimum: 1.0
    range: 0.15
    magic_resistance: 0.75
    intelligence: 0.25
   chance_of_removing_magic_effect:
    enable: true
    function:
    maximum: 0.25
    minimum: 0.0
    magic_resistance: 0.70
    intelligence: 0.2
    dexterity: 0.1
  on_player_shoot_bow:
   enable: true
   function:
   min_dexterity_for_max_precision: 50.0
   range: 1.5
  on_player_consume_potion:
   enable: true
   function:
   range: 0.1
   maximum: 2.0
   minimum: 1.0
   intelligence: 1.0
  player_attributes:
   movement_speed:
    enable: true
    function:
    maximum: 0.4
    minimum: 0.15
    agility: 1.0
    dexterity: 0.0
   attack_speed:
    enable: true
    function:
    maximum: 15.0
    minimum: 2.0
    agility: 0.85
    dexterity: 0.15
    strength: 0.0
   total_mana:
    enable: true
    function:
    intelligence: 1.0
   total_health:
    enable: true
    function:
    heath: 1.0
   mana_regen:
    enable: true
    function:
    maximum: 5.0
    minimum: 0.0
    intelligence: 1.0
   luck:
    enable: true
    function:
    maximum: 512
    minimum: 0
    intelligence: 0.85
    dexterity: 0.0
    agility: 0.15
   knockback_resistance:
    enable: true
    function:
    maximum: 0.99
    minimum: 0.0
    strength: 0.5
    dexterity: 0.0
    agility: 0.0
    defence: 0.5
   mob_follow_range:
    enable: true
    function:
    maximum: 1
    minimum: 64
    agility: 0.5
    intelligence: 0.25
    dexterity: 0.25




