# Each class has 88 points at start
# You can edit to your preference
# But don't touch the id
#
# healt with increase player maximum life
# strength will increase player damage with hand weapon or bow(but less). Will increase bow distance
# intelligence will increase player resistance to magic(less), increase damage with potion and increase chance of random effects with weapons
# dexterity will increase bow shooting precision and bow damage
# defence will reduce damage(except for potion)
# magic resistance will reduce damage taken from potion and reduce chance of weapon random effects
#
Class:
  Knight: 
    id: 1
    health: 22
    strength: 20
    intelligence: 10
    dexterity: 10
    defence: 16
    magicResistance: 10
  Paladin:
    id: 2
    health: 20
    strength: 24
    intelligence: 4
    dexterity: 8
    defence: 22
    magicResistance: 10
  Mage:
    id: 3
    health: 16
    strength: 6
    intelligence: 22
    dexterity: 14
    defence: 8
    magicResistance: 22
  Archer:
    id: 4
    health: 17
    strength: 11
    intelligence: 10
    dexterity: 26
    defence: 10
    magicResistance: 14


# first_lvl_exp: experience needed for the first level
# max_lvl: maximum level
# max_stats: maximum attributes for each stats
# next_lvl_exponential: experience needed for next level =  nextlvl += nextlvl * <number>
# can_switch_class: allow player to switch class. Will modify attributes based on the class difference
# allow_stats_reset: allow player to reset stats. Will reset stats to current class base attributes
# points_per_lvl: the amounts of points a player gets on every lvl up
# starting_points: number of points player get when first join
# auto_save: enable automatic saving
# save_interval: interval in seconde between each save
# exp_loss_on_death: amount(%) of experience loss when player dies
# exp_on_player_kill: base experiece when player kills another player. Will increase if the lvl difference is high


Settings:
  first_lvl_exp: 75
  max_lvl: 99
  max_stats: 99
  next_lvl_exponential: 1.5
  can_switch_class: false
  allow_stats_reset: true
  points_per_lvl: 1
  starting_points: 3
  auto_save: true
  save_interval: 360
  exp_loss_on_death: 25
  exp_on_player_kill: 25
