main: lowbrain.mcrpg.main.Main
name: LowbrainMCRPG
version: 1.1.0
author: Lowbrain
softdepend: [HolographicDisplays]
description: Add a tones of rpg elements to the game. Such as attributes, skills, spells, new items (armor, weapon, staff), races, classes, etc.
permission:
 mcrpg.save-all:
  description: save all connected player stats
 mcrpg.save:
  description: save you own stats
 mcrpg.stats-others:
  description: show other players stats
 mcrpg.reload:
  description: reload plugin
 mcrpg.setattributes-others:
  description: set / change other players attributes by command
commands:
   mcrpg:
      usage: |
                  Use /help mcrpg [subcommand] for more information
                  /mcrpg stats - show your player stats
                  /mcrpg stats <player> - show stats of player
                  /mcrpg classes - show all class basic attributes
                  /mcrpg setclass <name> - set your class
                  /mcrpg setclass rdm/random - set a random class
                  /mcrpg races - show all races basic attributes
                  /mcrpg setrace <name> - set your race
                  /mcrpg setrace rdm/random - set a random race
                  /mcrpg cast <spell name> - cast a spell to yourself
                  /mcrpg cast <spell name> <player name> - cast a spell to someone
                  /mcrpg togglestats <false or true> - hide or show stats scoreboard
                  /mcrpg togglestats <0 or 1> - hide or show stats scoreboard
                  /mcrpg togglestats - toggle stats scoreboard

                  /mcrpg mobkills <name> - show how many time you killed this mob
                  /mcrpg mobkills - show the number of kills you got for each mob

                  /mcprg skills - show the list of skills and their current level
                  /mcrpg setskill <name> - set the current skill to be used
                  /mcrpg upskill <name> - upgrade skill
                  /mcrpg getskill - get current skill
                  /mcrpg skill <name> - get the skill description
                  /mcrpg myskill <name> - get the skill info (level)

                  /mcrpg add defence <number>  - add <number> defence or def
                  /mcrpg add strength <number>  - add <number> strength o str
                  /mcrpg add health <number>  - add <number> health or hp
                  /mcrpg add dexterity <number>  - add <number> dexterity or dext
                  /mcrpg add magicResistance <number>  - add <number> magicResistance or mr
                  /mcrpg add intelligence <number>  - add <number> intelligence or int
                  /mcrpg add agility <number> - add <number> agility or ag
                  /mcrpg +defence - add 1 defence
                  /mcrpg +def - add 1 defence
                  /mcrpg +strength - add 1 strength
                  /mcrpg +str - add 1 strength
                  /mcrpg +health - add 1 health
                  /mcrpg +hp - add 1 health
                  /mcrpg +dexterity - add 1 dexterity
                  /mcrpg +dext - add 1 dexterity
                  /mcrpg +magicResistance - add 1 magic resistance
                  /mcrpg +mr - add 1 magic resistance
                  /mcrpg +agility - add 1 agility
                  /mcrpg +ag - add 1 agility

                  /mcrpg reset - reset your attributes to your default class
                  /mcrpg completereset true - reset you whole character (incluing level gained and xp)
                  /mcrpg reset <class> - reset your attributes to your new class
                  /mcrpg reset <class> <race>  - reset your attributes to your new class and new race
                  /mcrpg nextlvl - show how much xp is need for next lvl
                  /mcrpg save-all - save all player stats
                  /mcrpg save - save your stats
                  /mcrpg xp - amount of xp needed left to achieve next level




