main: lowbrain.mcrpg.main.Main
name: LowbrainMCRPG
version: 1.0.7
author: Lowbrain
description:
commands:
   mcrpg:
      usage: |
                  Use /help mcrpg [subcommand] for more information
                  /mcrpg stats - show your player stats
                  /mcrpg stats <player> - show stats of player
                  /mcrpg classes - show all class basic attributes
                  /mcrpg setclass <number> - set your class [1,2,3,4]
                  /mcrpg add defence <number > 0> - add <number> defence or def
                  /mcrpg add strength <number > 0> - add <number> strength o str
                  /mcrpg add health <number > 0> - add <number> health or hp
                  /mcrpg add dexterity <number > 0> - add <number> dexterity or dext
                  /mcrpg add magicResistance <number > 0> - add <number> magicResistance or mr
                  /mcrpg add intelligence <number > 0> - add <number> intelligence or int
                  /mcrpg +defence or +def - add 1 defence
                  /mcrpg +strength or +str - add 1 strength
                  /mcrpg +health or +hp - add 1 health
                  /mcrpg +dexterity or +dext - add 1 dexterity
                  /mcrpg +magicResistance or +mr - add 1 magic resistance
                  /mcrpg reset - reset your attributes to your default class
                  /mcrpg reset <new class number> - reset your attributes to your new class
                  /mcrpg nextlvl - show how much xp is need for next lvl
                  /mcrpg save-all - save all player stats
                  /mcrpg save - save your stats
                  /mcrpg xp - amount of xp needed left to achieve next level




