main: lowbrain.mcrpg.main.Main
name: LowbrainMCRPG
version: 1.0.4
author: Lowbrain
softdepend: [HolographicDisplays]
description:
commands:
   mcrpg:
      usage: |
                  Use /help mcrpg [subcommand] for more information
                  /mcrpg stats - show your player stats
                  /mcrpg stats <player> - show stats of player
                  /mcrpg classes - show all class basic attributes
                  /mcrpg setclass <name> - set your class
                  /mcrpg setclass rdm/random - set a random class
                  /mcrpg races - show all races basic attributes
                  /mcrpg setrace <name> - set your race
                  /mcrpg setrace rdm/random - set a random race
                  /mcrpg cast <spell name> - cast a spell to yourself
                  /mcrpg cast <spell name> <player name> - cast a spell to someone
                  /mcrpg togglestats <false or true> - hide or show stats scoreboard
                  /mcrpg togglestats <0 or 1> - hide or show stats scoreboard
                  /mcrpg togglestats - toggle stats scoreboard

                  /mcrpg add defence <number>  - add <number> defence or def
                  /mcrpg add strength <number>  - add <number> strength o str
                  /mcrpg add health <number>  - add <number> health or hp
                  /mcrpg add dexterity <number>  - add <number> dexterity or dext
                  /mcrpg add magicResistance <number>  - add <number> magicResistance or mr
                  /mcrpg add intelligence <number>  - add <number> intelligence or int
                  /mcrpg +defence - add 1 defence
                  /mcrpg +def - add 1 defence
                  /mcrpg +strength - add 1 strength
                  /mcrpg +str - add 1 strength
                  /mcrpg +health - add 1 health
                  /mcrpg +hp - add 1 health
                  /mcrpg +dexterity - add 1 dexterity
                  /mcrpg +dext - add 1 dexterity
                  /mcrpg +magicResistance - add 1 magic resistance
                  /mcrpg +mr - add 1 magic resistance
                  /mcrpg +agility - add 1 agility
                  /mcrpg +ag - add 1 agility

                  /mcrpg reset - reset your attributes to your default class
                  /mcrpg completereset true - reset you whole character (incluing level gained and xp)
                  /mcrpg reset <class> - reset your attributes to your new class
                  /mcrpg reset <class> <race>  - reset your attributes to your new class and new race
                  /mcrpg nextlvl - show how much xp is need for next lvl
                  /mcrpg save-all - save all player stats
                  /mcrpg save - save your stats
                  /mcrpg xp - amount of xp needed left to achieve next level




