
# don't touch these, they are use to notice admin of config changes
versions:
 classes: 1.0
 config: 1.0
 itemsrequirements: 1.0
 mobsxp: 1.0
 powers: 1.0
 races: 1.0
 skills: 1.0
 internationalization: 1.0
 parameters: 1.0

# set an hardcore mod
# if a player dies more than the defined max deaths, all stats will be reset
hard_core:
 enable: false
 max_deaths: 1

# disable mob no tick damage
disable_mob_no_tick_damage: true

# reduce the spawn of animal by breeding. default set to 50% chance of spawning
reduce_breeding_spawn: 0.5

# sets if ops bypass permissions
op_bypass_permission: true

# experience needed for the first level
first_lvl_exp: 75

# maximum level. value from 0 to -infinite = infinite number of level
max_lvl: 100

# maximum attributes for each stats. zero and negative values = infinite
# if set to an infinite value (<0), default value of 100 will be used when needed in mathematics
max_stats: 100

# allow player to deduct attributes. for example : /core add strength -1
allow_deduction_points: false

# allow player to switch class. it will apply attributes changes accordingly
can_switch_class: false

# allow player to switch race. it will aplly attributes changes accordingly
can_switch_race: false

# allow player to reset stats. it will reset to default race and class. player will keep is level and gained points
allow_stats_reset: false

# allow player to reset stats complitetely. will remove class and race. will also reset points and gained level
allow_complete_reset: true

# number of points a player gains on each level up
points_per_lvl: 2

# number of points a player gets a start
starting_points: 3

# number of skillpoints a player gets a start
starting_skill_points: 0

# the interval at wich players gain skillpoints
skill_points_level_interval: 5

# the number of skillpoints gained at each interval
skill_points_per_interval: 1

 # enable auto saving
auto_save: true

# auto saving interval in second(6min by default). auto_save must be true
save_interval: 360

# debug mode. show stuff in console
debug: true

# interval between each mana regen for all connected players.
# if you change this value, you must rebalance mana regeneration mathematics.
mana_regen_interval: 5

# set the server difficulty depending on average player level
automatic_server_difficulty:
 enable: true
 easy:
  from: 0
  to: 25
 medium:
  from: 26
  to: 55
 hard:
  from: 56
  to: -1

# shares xp between closed range player
group_xp:
 enable: true
 # enable Parties(plugin) group ex share (Parties must be installed)
 enable_parties: true
 # the amount of experience the player who killed the entity gets (%)
 main: 0.666
 # the rest is distributed equaly between other players
 others: 0.333
 # range in blocks
 range: 15

# Name of the files that contains the "mathematics" parameters
# This way, you can create multiple files to test different settings
# (eg : easy_parameters.yml, hard_parameters.yml, etc )
parameters_file: default_parameters.yml







