main: lowbrain.core.main.LowbrainCore
name: LowbrainCore
version: 0.0.1
author: Lowbrain
depend: [LowbrainLibrary]
softdepend: [HolographicDisplays , ArmorEquipEvent, PacketListenerApi, Parties, LowbrainItems]
description: Add a tones of rpg elements to the game. Such as attributes, skills, spells, new items (armor, weapon, staff), races, classes, etc.
permission:
 lb.core.save-all:
  description: save all connected player stats
  default: op
 lb.core.save:
  description: save you own stats
  default: op
 lb.core.stats-others:
  description: show other players stats
  default: op
 lb.core.reload:
  description: reload plugin
  default: op
 lb.core.setattributes-others:
  description: set / change other players attributes by command
  default: op
commands:
   core:
      usage: |
                  Use /help lbcore [subcommand] for more information
                  /lbcore stats - show your player stats
                  /lbcore stats <player> - show stats of player
                  /lbcore classes - show all class basic attributes
                  /lbcore setclass <name> - set your class
                  /lbcore setclass rdm/random - set a random class
                  /lbcore races - show all races basic attributes
                  /lbcore setrace <name> - set your race
                  /lbcore setrace rdm/random - set a random race
                  /lbcore cast <spell name> - cast a spell to yourself
                  /lbcore cast <spell name> <player name> - cast a spell to someone
                  /lbcore togglestats <false or true> - hide or show stats slbcoreboard
                  /lbcore togglestats <0 or 1> - hide or show stats slbcoreboard
                  /lbcore togglestats - toggle stats slbcoreboard
                  /lbcore showstats - toggle on stats slbcoreboard
                  /lbcore hidestats - toggle off stats slbcoreboard

                  /lbcore mobkills <name> - show how many time you killed this mob
                  /lbcore mobkills - show the number of kills you got for each mob

                  /lbcore skills - show the list of skills and their current level
                  /lbcore setskill <name> - set the current skill to be used
                  /lbcore upskill <name> - upgrade skill
                  /lbcore getskill - get current skill
                  /lbcore skill <name> - get the skill description
                  /lbcore myskill <name> - get the skill info (level)
                  /lbcore mypowers - show your available powers

                  /lbcore add defence <number>  - add <number> defence or def
                  /lbcore add strength <number>  - add <number> strength o str
                  /lbcore add vitality <number>  - add <number> vitality or hp
                  /lbcore add dexterity <number>  - add <number> dexterity or dext
                  /lbcore add magicResistance <number>  - add <number> magicResistance or mr
                  /lbcore add intelligence <number>  - add <number> intelligence or int
                  /lbcore add agility <number> - add <number> agility or ag
                  /lbcore +defence - add 1 defence
                  /lbcore +def - add 1 defence
                  /lbcore +strength - add 1 strength
                  /lbcore +str - add 1 strength
                  /lbcore +vitality - add 1 vitality
                  /lbcore +hp - add 1 vitality
                  /lbcore +dexterity - add 1 dexterity
                  /lbcore +dext - add 1 dexterity
                  /lbcore +magicResistance - add 1 magic resistance
                  /lbcore +mr - add 1 magic resistance
                  /lbcore +agility - add 1 agility
                  /lbcore +ag - add 1 agility

                  /lbcore reset - reset your attributes to your default class
                  /lbcore completereset true - reset you whole character (incluing level gained and xp)
                  /lbcore reset <class> - reset your attributes to your new class
                  /lbcore reset <class> <race>  - reset your attributes to your new class and new race
                  /lbcore nextlvl - show how much xp is need for next lvl
                  /lbcore save-all - save all player stats
                  /lbcore save - save your stats
                  /lbcore xp - amount of xp needed left to achieve next level




